### ISSUE TITLE
QCELS for QAGC

### ISSUE THREAD

**Issue by Connorpl** [QunaSys/quantum-algorithm-grand-challenge-2024#5]
## Team name: 
KCL Quantum

## Team members: 
Connor Lenihan
Avner Bensoussan
Elena Chachkarova
Karine Even-Mendoza
Sophie Fortz

## Project Description: 
The Quantum Complex Exponential Least Squares (QCELS) algorithm (Ding, Lin 2023) takes a reference state and evolves it by the time evolution operator enclosed within a Hadamard test. If the reference state is the ground state then the resultant expectation values are a single phase complex exponential and if the reference state is not exact then the resultant function contains extra phases from the excited states. Thus, if a reference state with good overlap with the true ground state is known, we can apply the time evolution operator within a Hadamard test n times and fit to the resulting complex exponential, refining our guess by allowing multiple energies to contribute.  For this challenge the Hartree-Fock ground state retains a reasonable overlap with the true ground state up to 28 qubits and the time evolution operator can be implemented with a first order Trotter-Suzuki expansion with a truncated Hamiltonian to reduce gate count.

## Presentation:
[QCELS for QAGC.pdf](https://github.com/user-attachments/files/16044113/QCELS.for.QAGC.pdf)

## Source code: 
https://github.com/Connorpl/QCELS_for_QAGC/blob/main/QCELS_answer.py

## Your score (Optional)
E_gs = -30.4 on a single test run

**Comment by masahikokamoshita** [comment]
**[Request for confirmation of code]**
Thanks for submitting. I got the error message listed below for five out of ten runs. 
It seems that In all of the runs, the submitted code calculated and calculated the x_points and y_points with no error, although half of them ended up with error in the fitting function.

If there are any minor bugs (please do not change the whole code) or it is regarding to the python environment problem, please let us know so that we can recalculate.

```
<class 'ValueError'>: Each lower bound must be strictly less than each upper bound.
Traceback (most recent call last):
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue5/evaluator.py", line 49, in get_accuracy
    energy, n_shots = run_algorithm.result_for_evaluation(seed, hamiltonian_directory)
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue5/answer.py", line 210, in result_for_evaluation
    energy_final = self.get_result(seed, hamiltonian_directory)
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue5/answer.py", line 291, in get_result
    E_gs = fit(x_points,y_points)
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue5/answer.py", line 147, in fit
    result3 = least_squares(residual_func3,p0,args=(y_points,x_points),bounds=([0.,-np.inf,0.,-0.8*abs(x_best[1]),-0.8*abs(result2.x[3])],[1,0.,abs(x_best[0]),0.8*abs(x_best[1]),0.8*abs(result2.x[3])]))
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.14/lib/python3.10/site-packages/scipy/optimize/_lsq/least_squares.py", line 816, in least_squares
    raise ValueError("Each lower bound must be strictly less than each "
ValueError: Each lower bound must be strictly less than each upper bound.
```

**Comment by Connorpl** [comment]
I can only see that error being caused by one of the fitting parameters being exactly zero, it shouldn't happen if the fitting procedure is working well but I've put in a quick fix for that by including a small epsilon parameter so it at least should not crash
