### ISSUE TITLE
Solving Fermi Hubbard using Variational Adiabatic Quantum Eigensolver and  Iterative Qubit Coupled Cluster

### ISSUE THREAD

**Issue by vivek-kumar9696** [QunaSys/quantum-algorithm-grand-challenge-2024#9]
## Team name: 
AJV Innovators

## Team members: 
Asim Sharma
John Burke
Vivek Kumar

## Project Description: 
A brief description of your project (1-2 paragraphs). 

## Presentation:
A link of presentation with slides of your team’s hackathon project.

## Source code: 
https://github.com/vivek-kumar9696/QAGC_2024_Fermi-Hubbard-Adiabatic

## Your score (Optional)
This will be used for reference during score evaluation. The results from less than ten calculation are also acceptable

**Comment by masahikokamoshita** [comment]
Hello thanks for submitting, I would like to inform you that your submitted code ended up with error. 
Attatched is the messages below. If there are any minor bugs please let us know soon so that we can recalculate.
```
Optimizer converged
<quri_parts.circuit.circuit_linear_mapped.LinearMappedUnboundParametricQuantumCircuit object at 0x7fc92c19ed40>
<class 'ValueError'>: The indices of the gate applied must be smaller than qubit_count
Traceback (most recent call last):
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue09/evaluator.py", line 49, in get_accuracy
    energy, n_shots = run_algorithm.result_for_evaluation(seed, hamiltonian_directory)
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue09/answer.py", line 158, in result_for_evaluation
    energy_final = self.get_result(seed, hamiltonian_directory)
  File "/home/users/quantum-algorithm-grand-challenge-2024/issue09/answer.py", line 213, in get_result
    new_param_index = new_circuit.add_RY_gate(qubit, np.random.rand())
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.14/lib/python3.10/site-packages/quri_parts/circuit/circuit.py", line 175, in add_RY_gate
    self.add_gate(RY(index, angle))
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.14/lib/python3.10/site-packages/quri_parts/circuit/circuit_linear_mapped.py", line 170, in add_gate 
    self._circuit.add_gate(gate, gate_index)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.14/lib/python3.10/site-packages/quri_parts/circuit/circuit_parametric.py", line 320, in add_gate
    raise ValueError(
ValueError: The indices of the gate applied must be smaller than qubit_count
None
```

**Comment by masahikokamoshita** [comment]
Hello, I would like to hear your response by this Wednesday (7/24 25:59 JST), otherwise your team's score may be invalidated since we cannot calculate the score
